use BookStore;

CREATE TABLE Books
(
	[BookID] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	[Author] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500) NOT NULL,
	[Genre] NVARCHAR(50) NOT NULL,
	[Price] DECIMAL(16, 2) NOT NULL
)